name: release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip
          pip install build --user

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPY_API_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict,docs]

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_labels: dependencies

      - name: Commit files
        run: |
          git config --local user.email "mcdermott@lbl.gov"
          git config --local user.name "materialsproject"
          git stash
          git pull origin main
          mv CHANGELOG.md docs/
          git add docs/CHANGELOG.md && git commit -m 'Updated CHANGELOG.md'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
